<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ggPerfectmoney\Module'           => __DIR__ . '/Module.php',
    'ggPerfectmoney\Form\PaymentForm' => __DIR__ . '/src/Form/PaymentForm.php',
);