<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ggPerfectmoney\Module'                       => __DIR__ . '/Module.php',
    'ggPerfectmoney\Controller\DepositController' => __DIR__ . '/src/ggPerfectmoney/Controller/DepositController.php',
    'ggPerfectmoney\Form\StatusForm'              => __DIR__ . '/src/ggPerfectmoney/Form/StatusForm.php',
    'ggPerfectmoney\Form\PaymentForm'             => __DIR__ . '/src/ggPerfectmoney/Form/PaymentForm.php',
);
