<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'zfPerfectmoney\Module'                       => __DIR__ . '/Module.php',
    'zfPerfectmoney\Controller\DepositController' => __DIR__ . '/src/zfPerfectmoney/Controller/DepositController.php',
    'zfPerfectmoney\Form\StatusForm'              => __DIR__ . '/src/zfPerfectmoney/Form/StatusForm.php',
    'zfPerfectmoney\Form\PaymentForm'             => __DIR__ . '/src/zfPerfectmoney/Form/PaymentForm.php',
);
